import SaSCover from "./postMedia/SurpriseAndSerendipity/SurpriseAndSerendipity_cover.png"
import templateCover from "./postMedia/template/template_cover.png"
import WritingOnTheWindCover from "./postMedia/WritingOnTheWind/WritingOnTheWind_cover.png"

export const posts = [
    {
        title: "Surprise and Serendipity in the Old West",
        to: "SurpriseAndSerendipityInTheOldWest",
        subtitle: "On Keeping an Open Mind Beneath the Big Sky",
        date: "June 9, 2023",
        cover: SaSCover,
        alt: "Sunset in Glacier National Park",
        body: ["We were somewhere around Sarnia on the edge of the nation when the reality began to take hold. I remember hearing something like “I didn’t think of a place to sleep tonight; ‘figured we’d just drive...”.  And drive we did. Nervously clutching our final Tim Horton’s coffee’s, we crossed the border and set off toward the unknown. Destination: Missoula, Montana. All other details: TBD.", <br></br>,<br></br>,

            "When Dylan and Ingrid called me up that spring day and proposed this road trip, I knew that my initial hesitation was but a front – two weeks gallivanting around the Rockies with two of my best friends, living on the cheap and keeping our minds free, is not the type of adventure that I would turn down lightly. The ostensible reason for our journey was to attend the conference of the Gap Year Association, an annual meeting of the greatest minds in the industry of keeping kids out of school – a cause close to Dylan’s heart and one which he is personally hoping to further. The conference would play out over three days in Missoula, a final hippie holdout in the heart of the Headwaters State. While Dylan rubbed shoulders with the biggest hitters in his field, Ingrid and I would be free to explore the city’s plethora of cafe’s, record and instrument shops, and parks. Before any of this, though, our Grand Caravan would have to carry us across 3000km of interstate through forest, prairie, and Rocky mountain. ", <br></br>,<br></br>,

            <em>To be continued...</em>
        ],
    },
    {
        title: "Writing On The Wind: Starting a Blog in the Age of Short-Form Content",
        to: "WritingOnTheWind",
        subtitle: "One Man’s Mission to Improve His Thinking and Refine His Communication (and Score some Affiliate Links)",
        date: "June 2, 2023 ",
        cover: WritingOnTheWindCover,
        body: ["The idea for this blog has been kicking around my mind for quite some time. I have long been interested by the idea of writing as an exercise – as a practice. When I would hear authors and other guru-type figures espouse the value of long-form writing, there were three claims that always stood out. It is said that writing in full sentences – you know, the way we did in school – can hold benefits to one’s written communication (of course), as well as their verbal communication. There are claims that, since our thoughts consist of words, our thinking and decision-making abilities can be improved through writing. ", <br></br>, <br></br>,

            "Ultimately, the value of writing is undisputed. I’ve long kept a journal for working out particularly sticky points of my life, and I consider songwriting to be my craft. However, there is a final piece of the puzzle of why this blog is being conceived: by actually publishing our writing, we are forced to release it into the world knowing that while it may not be perfect, it is the best we can do right now. Any flaws will be laid bare, and feedback or criticism can be received and applied to make future work better. This process changes how we write, in a manner that I see as massively beneficial over writing in private.", <br></br>, <br></br>,

            "It’s not hard to see how the first and third benefits listed above fit together. This is how we learn to write as kids – by composing works and improving upon them based on the feedback received. What I find exciting about blogging is that it provides an opportunity to continue this process into adulthood, endowed with a greater understanding of my mind and how I learn than I ever had in grade school. My study of physics taught me to break problems down and work them within the structure of mathematics, communicating my results in the same language. For me, it clicked all too recently that this same process of stating definitions, connecting a train of logic, and arguing one’s result can be done using the English language, nearly as readily as one uses the purpose-built language of mathematics. This is the trade of lawyers and philosophers, and a critical skill for the rest of us as we seek to understand the world and advocate for our interests. The issue is that many of us fail to even attempt to express ourselves as fully and verbosely as we ought to, and whether out of laziness or consideration of other's time, this harms ourselves the most. Knowing that we’ve done the work to clearly lay out our views on a given issue puts some weight behind our spoken words and provides a foundation from which we may understand the world. In the age of TikTok and Twitter, blogging stands alone as an accessible way for all of us to practice the clear, thorough expression of our thoughts.", <br></br>, <br></br>,

            "Indeed, writing in long-form does even more for our own thinking than it does for our communication. Language is the tool of the mind – the very thoughts we use to make decisions and understand the world are composed of words and sentences, often chopped up and scrambled in a highly non-linear manner. Writing down one’s thoughts and findings is a powerful tool for sorting this tangled heap into something cohesive. The process of drafting and revision encourages us to dump our thoughts onto the page as they are, complete with all the half-truths and logical inconsistencies that call our minds home. We can then sort through the mess out in the open until it is boiled down to something approximating truth. It seems to me that this process would have been far more common for past generations, who corresponded through multi-page letters and frequently documented their experiences through journals and memoirs. In contrast, the rule today is brevity. Fragments of sentences rife with short-forms and acronyms, emails without introductions, and content without context. There is certainly something to be said for the efficiency that this style of communication provides; however, it makes it very easy for myths and fallacious thinking to linger beneath the surface. To view thinking as an active endeavor, taking place on paper or in a word document, remains a powerful defence against ignorance and one which everyone can benefit from adopting.", <br></br>, <br></br>,

            "My final justification for creating this blog is also the only one that pertains specifically to the blog format, rather than to writing in general. Blogs are meant to be read – whether they are read is besides the point. We express ourselves differently when we know that other people are watching; this is most pronounced in verbal exchanges, where a presenter falls entirely upon his slides, or an interviewee can’t think of a single reason that they’d like the job. A similar phenomenon does occur across distance, however, and can be seen in the tone of an email from a freshman student to a professor or in the hesitation of an inexperienced salesperson on a phone call. As people gain experience in any of these situations, their demeanor comes to resemble more closely that which they display amongst their friends: loose, open, confident. There is a feedback loop throughout our social interactions, wherein we repeat actions that are received favorably and abandon those that are not (nothing groundbreaking here). In my experience, the rate of negative feedback is relatively low – most people much prefer dishing out praise than criticism. The issue for our freshman student or greenhorn salesperson, then, is simply that they have not put themselves in enough “risky” situations to build confidence in their ability to emerge successful. I view blogging – publishing my raw, (if poorly edited) thoughts for the world to read (or not) as a risk. Nonetheless, it is the only way to go through the iterative process and improve my writing, and by direct extension my thinking and communication. It doesn’t much matter if anybody reads these words because the very fact that they are here to be read provides all the benefits of an audience.", <br></br>, <br></br>,

            "So that’s why we’re here. This blog is simply a selfish excuse for me to ramble about the things I care about, and hopefully reach some useful insights along the way. There will be no cohesion of topics, no consistency of publishing, and certainly no affiliate links. But if all goes to plan, I will be able to look back in a couple of years to remember the things that I once thought, that I once cared about. I hope that I am embarrassed by the way I once wrote, and that I can be glad of how far I’ve come. And then I’ll repeat the process. And then at some point I’ll stop. But by the time I do I’ll be a little bit older and hopefully a little bit wiser. Maybe I’ll be able to tell you about it here.",
        ],
    },
]